version: "3"

services:
  nodered:
    image: itaru2622/nodered:bullseye
    container_name: nodered
    hostname: nodered
    environment:
       - http_proxy=${http_proxy}
       - https_proxy=${https_proxy}
       - no_proxy=${no_proxy}
    #volumes:
    ports:
       - "1880:1880"
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - http_proxy=${http_proxy}
        - https_proxy=${https_proxy}
        - no_proxy=${no_proxy}

